### ISSUE TITLE
Issues on Raspberry Pi

### ISSUE THREAD

**Issue by DarkScientist** [eouia/MMM-Tools#10]
Hello, it's a very good module for MagicMirror working on a Raspberry pi !
All is working except the command to turn off / on the screen : nothing happens.

**Comment by E3V3A** [comment]
It's because [something was broken](https://github.com/raspberrypi/linux/issues/2517) with *xset* in the updates for Stretch. The code [here](https://github.com/eouia/MMM-Tools/blob/master/node_helper.js#L37-L38) need to be replaced: 

```js
  SCREEN_ON : "xset dpms force on",
  SCREEN_OFF : "xset dpms force off",
  SCREEN_STATUS : "xset q | grep 'Monitor is' | awk '{print $3}'",
```

**Comment by DarkScientist** [comment]
Thx !
