### ISSUE TITLE
Default config gives error in during startup

### ISSUE THREAD

**Issue by TheStigh** [eouia/MMM-Tools#12]
Hi @sean,

Installing MMM-Tools, using default config, gives error during 'npm start'

Tried minimal config:
		{
			module: 'MMM-Tools',
			position: 'bottom_right',
			config: {
				device : "RPI", // "RPI" is also available
			}
		},			

Still it gives error "WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration." during 'npm start'

**Comment by eouia** [comment]
Well, that error says commonly when you made syntax error (comma or bracket missed or added unnecessarily).

**Comment by TheStigh** [comment]
Well, it uses your default config :)
I only use the above to change default ATB to RPI, the rest is picked from your MMM-Tools.js

I now changed my config til be only:
		{

			module: 'MMM-Tools',
			position: 'bottom_right'
			
		},	

I also modified your MMM-Tools.js with replacing ATB with RPI, still, I get the same error during npm start.

**Comment by eouia** [comment]
remove whole configuration of MMM-Tools and try again.
If error is disappeared, MMM-Tools configuration would be the reason. (But as far as I see your config, there seems no suspicious point)
If error is still appeared, other section would be the reason.

**Comment by TheStigh** [comment]
I now changed my config til be only:
{
module: 'MMM-Tools',
position: 'bottom_right'
},

I also modified your MMM-Tools.js with replacing ATB with RPI, still, I get the same error during npm start.

PS; If I remove entire module from my config.js, MM starts just fine.

**Comment by eouia** [comment]
Give me a full config.js to examine.

**Comment by TheStigh** [comment]
> 
> 
> Give me a full config.js to examine.

Ok, I'll send it by email

**Comment by eouia** [comment]
As far as I know, this issue is solved. I'll close this issue. Have a nice day.
