### ISSUE TITLE
Is it possible to show the Pi´s power consumption? 

### ISSUE THREAD

**Issue by Starplayer84** [eouia/MMM-Tools#15]
It´s not really an Issue, but I don´t know where to mention this question...

Like I said in the toppic, is it possible to let your Module messure the actual power consumption of the Pi and show this on the screen?

**Comment by eouia** [comment]
First I don't know how to measure actual power consumption or Raspberry Pi by realtime with only software. Have you heard? I think it couldn't with only S/W
If you have a h/w to measure power consumption? if that H/W has I/O features, it might be possible, but in other cases, impossible.

**Comment by Starplayer84** [comment]
Okay thanks dir your fast andere!

**Comment by Starplayer84** [comment]
Okay no problem, thanks for your fast answer!
