### ISSUE TITLE
Cannot add additional command

### ISSUE THREAD

**Issue by FatTony123** [eouia/MMM-Tools#17]
I tried to add anthor command to a forked version of the tool using the same code: 

`getCommands : function(register) {
    if (register.constructor.name == 'TelegramBotCommandRegister') {
      register.add({
        command: 'status',
        description: this.translate("CMD_TELBOT_STATUS_DESCRIPTION"),
        callback: 'cmd_status'
      })
      register.add({
        command: 'screen',
        description: this.translate("CMD_TELBOT_SCREEN_DESCRIPTION"),
        callback: 'cmd_screen',
        args_pattern : [/^on|off/i],
        args_mapping : ['onoff']
      })
      register.add({
        command: 'capture',
        description: this.translate("CMD_TELBOT_CAPTURE_DESCRIPTION"),
        callback: 'cmd_capture'     
      })
      register.add({
        command: 'relay',
        description: this.translate("CMD_TELBOT_RELAY_DESCRIPTION"),
        callback: 'cmd_relay',
        args_pattern : [/^on|off/i],
        args_mapping : ['onoff']
      })
    }
    if (register.constructor.name == 'AssistantCommandRegister') {
      register.add({
        command: this.translate("CMD_ASSTNT_STATUS"),
        description: this.translate("CMD_ASSTNT_STATUS_DESCRIPTION"),
        callback: 'cmd_status',
      })
      register.add({
        command: this.translate("CMD_ASSTNT_SCREEN"),
        description: this.translate("CMD_ASSTNT_SCREEN_DESCRIPTION"),
        callback: 'cmd_screen',
      })
      register.add({
        command: this.translate("CMD_ASSTNT_CAPTURE"),
        description: this.translate("CMD_ASSTNT_CAPTURE_DESCRIPTION"),
        callback: 'cmd_capture',
      })
      register.add({
        command: this.translate("CMD_ASSTNT_RELAY"),
        description: this.translate("CMD_ASSTNT_RELAY_DESCRIPTION"),
        callback: 'cmd_relay',
      })
    }
  }`

However, the command never get's registered on TelegramBot.

**Comment by eouia** [comment]
I’ll examine on Monday 
And tell you.

**Comment by eouia** [comment]
Have you what kind of error was found at the execution? Show me the log or errors.

**Comment by eouia** [comment]
I'll close this issue because there is no more feedback. You can ask me anytime again.
