### ISSUE TITLE
Memory result not accurate 

### ISSUE THREAD

**Issue by ejay-ibm** [eouia/MMM-Tools#18]
Hi Sean 
I'm trying this tools and found out that some given number are not accurate For Memory 
 
This is a screen shot of the task manager 
![capture d ecran 2019-03-03 a 11 09 05](https://user-images.githubusercontent.com/38557267/53693745-d3de4180-3da4-11e9-841e-5fa2ad086bee.png)
and the free -h result 

free -h
                       total        used        free      shared       buff/cache   available
Mem:           927M        320M         45M        207M        558M        335M
Swap:          2,9G         76M        2,8G

I'll try to figure out a good calculation mode in command line to reflect the number in task manager

**Comment by eouia** [comment]
https://jameshfisher.com/2017/11/29/unix-free-used.html

**Comment by ejay-ibm** [comment]
pi@ejaypi:~$ head -5 /proc/meminfo 
MemTotal:         949448 kB
MemFree:           37648 kB
MemAvailable:     366824 kB
Buffers:           54560 kB
Cached:           455896 kB

The accurate result for memory used should be: 
(MemTotal-MemFree)  - > that give the Total used memory 
Total used memory - (Buffers + Cached memory)

In other word : 
MemTotal-MemFree)  - (Buffers + Cached memory)

I'll try to get the result of this in a single command line. I can't use awk as it process single record only. I would need to format the output in a single line first. 

Will report my findings soon.

**Comment by ejay-ibm** [comment]
ok something like this do the trick : 
````
MEMORY_TOTAL : "head -5 /proc/meminfo  | awk '{print}' ORS=' ' | awk '{print ($2)}'",
MEMORY_USED : " head -5 /proc/meminfo  | awk '{print}' ORS=' ' | awk '{print ($2-$5)-($11+$14)}'",
EMORY_USED_PERCENT : "head -5 /proc/meminfo  | awk '{print}' ORS=' ' | awk '{print (($2-$5)-($11+$14))/$2*100}'",

`````
Hope this helps 

Ejay

**Comment by ejay-ibm** [comment]
In reply to your link 
![capture d ecran 2019-03-03 a 12 05 37](https://user-images.githubusercontent.com/38557267/53694274-c5942380-3dac-11e9-904d-ef1034cdfb56.png)

the right calculation can only be done with -/+ buffers/cache:       1096       2668

But here is my output from free

pi@ejaypi:~$ free
              total        used        free      shared  buff/cache   available
Mem:         949448      303704       34460      215244      611284      365008
Swap:       3046592       80896     2965696


I don't have those number So calculation can't be done ( probably due to a particular version of free) Idk 

I think you should implement my suggestion in your code after testing 

I'll open another issue for the disk usage as I think it's not accurate as well . 

Ejay

**Comment by ejay-ibm** [comment]
Better to have Mem size in Mb

````
MEMORY_TOTAL: "head -5 /proc/meminfo  | awk '{print}' ORS=' ' | awk '{print ($2)/1024}'"
MEMORY_USED : "head -5 /proc/meminfo  | awk '{print}' ORS=' ' | awk '{print (($2-$5)-($11+$14))/1024}'",
````
But I'm getting number like : 924.14  I have not been able to remove the dot and char after to only keep 924 using unix bach command ( sed awk etc) 
Maybe it can be done later in the code .

**Comment by ejay-ibm** [comment]
Proposed code change and created pull request

**Comment by ejay-ibm** [comment]
MEMORY_TOTAL : "head -5 /proc/meminfo  | awk '{print}' ORS=' ' | awk '{print ($2)/1024}' | cut -f1 -d\".\" | sed 's/$/Mb/'",
  MEMORY_USED : "head -5 /proc/meminfo  | awk '{print}' ORS=' ' | awk '{print (($2-$5)-($11+$14))/1024}' | cut -f1 -d\".\" | sed 's/$/Mb/'",
  MEMORY_USED_PERCENT : "head -5 /proc/meminfo  | awk '{print}' ORS=' ' | awk '{print (($2-$5)-($11+$14))/$2*100}'",

**Comment by ejay-ibm** [comment]
Pull request approved. 
Closing Issue.
