### ISSUE TITLE
Disk Usage 

### ISSUE THREAD

**Issue by ejay-ibm** [eouia/MMM-Tools#19]
Hi Sean , 

Actual result from your code give : 

![capture d ecran 2019-03-03 a 12 27 50](https://user-images.githubusercontent.com/38557267/53694466-ced2bf80-3daf-11e9-97b7-463b90f995c1.png)

Commands should be : 
````
STORAGE_TOTAL : "df -h --total | grep 'total' | awk '{print $2}'",
STORAGE_USED : "df -h --total | grep 'total' | awk '{print $3}'",
STORAGE_USED_PERCENT : "df --total | grep 'total' | awk '{print $3/$2*100}'",
`````

result on my system 
df -h --total | grep total | awk '{print $2}'
30G
df -h --total | grep 'total' | awk '{print $3}'
8,9G
df --total | grep 'total' | awk '{print $3/$2*100}'
30.0917

Ejay

**Comment by ejay-ibm** [comment]
Proposed code change and created pull request

**Comment by ejay-ibm** [comment]
STORAGE_TOTAL : "df -h --total | grep total | awk '{print $2}'",
  STORAGE_USED : "df -h --total | grep 'total' | awk '{print $3}'",
  STORAGE_USED_PERCENT : "df --total | grep 'total' | awk '{print $3/$2*100}'",

**Comment by eouia** [comment]
Thanks for your inform. Frankly, I'm not an expert of this system kind. :D
Can you make a PR this and #18 ? I'll test and merge it.

The better way is this external command to be configurable.(Not only for this issue, But also for supporting other platform) I'll try it someday, but I'm on vacation now. :D

**Comment by ejay-ibm** [comment]
Pull request Approved 
Closing Issue
