### ISSUE TITLE
Screen status doesn’t appear

### ISSUE THREAD

**Issue by ezar** [eouia/MMM-Tools#27]
Using last version, when I use /status from telegram, doesn’t appear monitor status:

RAM Used : 39.1%,
SD Used : 80%,
CPU Temp. : 43.5°C,
GPU Temp. : 42.9°C,
Uptime : 15 hours, 9 minutes,
CPU Usage : 3%,
Display : .

When I use xset:

pi@magicmirror:~ $ xset q
xset:  unable to open display ""

**Comment by eouia** [comment]
Your `xset` on RPI seems not working. I don't know exactly why. (Sorry I'm not the expert of that kind)

**Comment by ezar** [comment]
:(

**Comment by eouia** [comment]
I'll close this issue. Wish a good luck.
