### ISSUE TITLE
Personalize & change language

### ISSUE THREAD

**Issue by JohnB7777** [eouia/MMM-Tools#28]
Hello,

I try to personalize and changing the language of this module but I don't know how to do.
For example : I want text in french and on the left, not on the right.

Thanks !

**Comment by eouia** [comment]
I added `fr` and `sv` now. update module, then Set your mirror locale to `fr` in configuration. Try it.
But Not tested enough, so if you find any improvements, Feel free to contribute with PR.
See translations directory. The basic template would be `en.json`. You can modify `fr.json` for French language.
