### ISSUE TITLE
Add some Icons/Symbols to every item  

### ISSUE THREAD

**Issue by p10dulkar** [eouia/MMM-Tools#33]
Hi 
This is not an  issue just an enhancement to gui request
Can u add Icons or symbols before the output or after the Row  just like this guy did it 
https://github.com/BenRoe/MMM-SystemStats

Btw love all ur work using all ur modules in my version 
and the great thing i love about ur modules that they r interconnected 
Thanks , Keep up the good work

**Comment by eouia** [comment]
I'm building new module to replace this module. wait a while.

**Comment by p10dulkar** [comment]
Gr8 thanks for responding 
But if possible can u give me a timeline 😁 only if possible so that I can follow up on it

**Comment by eouia** [comment]
Anyway, you can add/modify the label by manual.
Open `translations/en.json` https://github.com/eouia/MMM-Tools/blob/master/translations/en.json  (if you are using English) then modify the text.

By example;
```js
"IP" : "IP",
```
to
```js
"IP" : "<img src="..."> My IP",  // <-- Whatever you want.
```

**Comment by p10dulkar** [comment]
Gr8 Thanks 
Waiting for new Module
