### ISSUE TITLE
Bars/info value not displayed properly

### ISSUE THREAD

**Issue by slametps** [eouia/MMM-Tools#8]
![mm-tools-nodisplayproper](https://user-images.githubusercontent.com/20857805/32128296-db220fac-bba6-11e7-843d-2d5f41ed587f.png)
I got this. Can you help, what's wrong? I just pulled from the repo.

**Comment by eouia** [comment]
Hmmm... weird. Give me your config and customed css. I think it is related with css colison.

**Comment by slametps** [comment]
Here they are:
[config.js.txt](https://github.com/eouia/MMM-Tools/files/1424006/config.js.txt)
[custom.css.txt](https://github.com/eouia/MMM-Tools/files/1424007/custom.css.txt)

**Comment by slametps** [comment]
If I moved the MMM-Tools to `top_right`, everything works fine. I think you're right about css collision. I need to investigate further to make it works on `bottom_right`.

**Comment by eouia** [comment]
I think this makes problem
```
.region.bottom .container {
  margin-top: 25px;
}
```

**Comment by slametps** [comment]
Yap, I did it. Thx.

**Comment by eouia** [comment]
I'll close this issue.
The Next commit I'll change css for escaping that issue. Thx for using.
